version: '3'

services:
    leicia-discord:
        image: leicia-discord
        build: .
        container_name: leicia-discord
        ports:
            - 3090:3090
        environment:
            - PGID=1000
            - PUID=1000
            - MONGO_HOST=${MONGO_HOST}
            - MONGO_USER=${MONGO_ROOT_USER}
            - MONGO_PASS=${MONGO_ROOT_PASSWORD}
        restart: always
        depends_on:
            - mongo

    mongo:
        image: mongo
        container_name: mongodb
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
        volumes:
            - ./db-data:/data/db
        restart: 'always'
